In [1]:
import pandas as pd

In [2]:
# Criação de DataFrame
dados = {
    'Nome': ['Arthur', 'Edenilson', 'Pedro Lucas', 'Luiz Felipe'],
    'Idade': ['25', '45', '20', '20'],
    'Cidade': ['Baía Formosa', 'São José de Mipibu', 'Canguaretama', 'Canguaretama'],
    'Turma': ['TSI 2021.1', 'TSI 2021.1', 'TSI 2021.1', 'TSI 2021.1']
}

df_dados = pd.DataFrame(dados)
df_dados

          Nome Idade              Cidade       Turma
0       Arthur    25        Baía Formosa  TSI 2021.1
1    Edenilson    45  São José de Mipibu  TSI 2021.1
2  Pedro Lucas    20        Canguaretama  TSI 2021.1
3  Luiz Felipe    20        Canguaretama  TSI 2021.1

In [7]:
# Dados fictícios
dados = {
    'Nome completo': ['João Silva', 'Maria Oliveira', 'Carlos Santos'],
    'Data de nascimento': ['1995-03-10', '1998-08-22', '1993-05-15'],
    'Turma': ['A', 'B', 'C'],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte'],
    'A região em que mora': ['Sudeste', 'Sudeste', 'Sudeste'],
    'Ensino médio': ['Completo', 'Completo', 'Completo'],
    'Situação da Matrícula': ['Ativo', 'Ativo', 'Desistente'],
    'Semestres Cursando': [5, 6, 4],
    'Semestre Desistência': [None, None, 3],  # Preencha com valores reais, se aplicável
    'Modalidade estágio': ['Sim', 'Não', 'Sim'],
    'Satisfeito(a) com o estágio de TI': ['Sim', 'Não', 'Sim'],
    'Concluiu, começou ou continuou a trabalhar após o curso': ['Sim', 'Não', 'Sim'],
    'Modalidade Trabalho após o curso': ['Emprego fixo', 'Freelance', 'Emprego fixo'],
    'Área que Trabalhou/trabalha na TI': ['Desenvolvimento web', 'Suporte técnico', 'Redes'],
    'Áreas estágio': ['Desenvolvimento de software', 'Suporte técnico', 'Redes'],
    'Subáreas mais se identifica': ['Front-end', 'Help Desk', 'Segurança da Informação'],
    'Publicação acadêmica': ['Sim', 'Não', 'Não'],
    'Projetos': ['Projeto A', 'Projeto B', 'Projeto C'],
    'Confirmação de intercâmbio': ['Sim', 'Não', 'Não']
}

# Criando o DataFrame
df_alunos = pd.DataFrame(dados)

# Exibindo o DataFrame
df_alunos

,Nome completo,Data de nascimento,Turma,Cidade,A região em que mora,Ensino médio,Situação da Matrícula,Semestres Cursando,Semestre Desistência,Modalidade estágio,Satisfeito(a) com o estágio de TI,"Concluiu, começou ou continuou a trabalhar após o curso",Modalidade Trabalho após o curso,Área que Trabalhou/trabalha na TI,Áreas estágio,Subáreas mais se identifica,Publicação acadêmica,Projetos,Confirmação de intercâmbio
0,João Silva,1995-03-10,A,São Paulo,Sudeste,Completo,Ativo,5,NaN,Sim,Sim,Sim,Emprego fixo,Desenvolvimento web,Desenvolvimento de software,Front-end,Sim,Projeto A,Sim
1,Maria Oliveira,1998-08-22,B,Rio de Janeiro,Sudeste,Completo,Ativo,6,NaN,Não,Não,Não,Freelance,Suporte técnico,Suporte técnico,Help Desk,Não,Projeto B,Não
2,Carlos Santos,1993-05-15,C,Belo Horizonte,Sudeste,Completo,Desistente,4,3.0,Sim,Sim,Sim,Emprego fixo,Redes,Redes,Segurança da Informação,Não,Projeto C,Não

In [12]:
df_alunos = pd.DataFrame(dados)

df_alunos.rename(columns={'Nome': 'Nomecompleto'}, inplace=True)
df_alunos

,Nome completo,Data de nascimento,Turma,Cidade,A região em que mora,Ensino médio,Situação da Matrícula,Semestres Cursando,Semestre Desistência,Modalidade estágio,Satisfeito(a) com o estágio de TI,"Concluiu, começou ou continuou a trabalhar após o curso",Modalidade Trabalho após o curso,Área que Trabalhou/trabalha na TI,Áreas estágio,Subáreas mais se identifica,Publicação acadêmica,Projetos,Confirmação de intercâmbio
0,João Silva,1995-03-10,A,São Paulo,Sudeste,Completo,Ativo,5,NaN,Sim,Sim,Sim,Emprego fixo,Desenvolvimento web,Desenvolvimento de software,Front-end,Sim,Projeto A,Sim
1,Maria Oliveira,1998-08-22,B,Rio de Janeiro,Sudeste,Completo,Ativo,6,NaN,Não,Não,Não,Freelance,Suporte técnico,Suporte técnico,Help Desk,Não,Projeto B,Não
2,Carlos Santos,1993-05-15,C,Belo Horizonte,Sudeste,Completo,Desistente,4,3.0,Sim,Sim,Sim,Emprego fixo,Redes,Redes,Segurança da Informação,Não,Projeto C,Não